### ISSUE TITLE
The recipe for crude science requires stone brick

### ISSUE THREAD

**Issue by jtinbergen** [Factorio-Xander-Mod/Xander_Mod_3#3]
Unfortunately, it is not clear how to automate the production of these bricks.

A building should exist where you can create them.

**Comment by Repofme1** [comment]
They can be made in the steam and electric 1 machine tools (tier 0 and 1), stone bricks are much easier to chip and cut than melt.  I added the made-in machine label to most recipes for clarity, which will be in the next update.  I didn't actually know how to do that until your issue motivated me to learn it.

**Comment by Repofme1** [comment]
Fixed with XM 3.4.3 update.
