### ISSUE TITLE
Assembling machine requires to produce improved assembling machine

### ISSUE THREAD

**Issue by Highlander37** [Factorio-Xander-Mod/Xander_Mod_3#4]
Hello, Repofme1

I found some case, that can be issue. 

I trying to build Assembling machine in automatic mode. Looks like Assembling machine can be build only in improved assembling machine. I think it's bug, because in vanilla game assebling machine canb be build in itself.

Now I should build Assembling machine im manual mode (by character) while i can't create improved assembling machine.

if this behavior is not due to the idea of a mod - can you allow build Assembling machine in itself ?

**Comment by Repofme1** [comment]
Hi there Highlander -

It is actually my intention that the burner and electric level 1 assembling machines cannot craft themselves.  I was thinking about it and decided that, even starting from component parts, making a machine that can replicate itself is no easy task!  Even currently, the technology to do this in real life is fairly limited.  I understand that automatic production of all kinds of machines is an important gameplay feature, and critical for large bases.  However, in my test world, I have been able to reach the technology to produce the assembling machine 2 without excessive difficulty.  By stocking a variety of materials and parts in my inventory, hand-crafting level 1 electric machines 10 at a time has easily met my needs, and has made only a small contribution to the challenge of playing the mod.  From this, I feel that the assembling machine 2 is an acceptable technology level for the first automatic crafting of production machines.
